title: "MetaSounds Official Site | MetaSounds"
description: ""
baseurl: ""
url: "https://metasoundsproject.github.io"
menus: header

exclude: 
  - demo/
  - Gemfile
  - vendor
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png
  
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
